name: Build Libretro macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: |
          make -f Makefile.libretro \
            platform=osx \
            -j$(sysctl -n hw.ncpu)
